# Generated by Django 3.1.4 on 2020-12-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
