# Generated by Django 3.1.4 on 2020-12-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201208_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='desc',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
